### ISSUE TITLE
Add basic bookmarking feature

### ISSUE THREAD

**Issue by heyitsolivia** [heyitsolivia/10k-gutenburg#11]
- [ ] Application should keep track of the last page of each book you read
- [ ] Opening a book should take you to the last page you were on
- [ ] Books that you have opened should have a visual indicator (maybe if you have read beyond page 1?). Indicator could be a literal bookmark on the book cover.

**Comment by janrubio** [comment]
New "continue from p.#" as example for conditional element with available page number

<img width="327" alt="screen shot 2016-09-30 at 4 33 07 am" src="https://cloud.githubusercontent.com/assets/1198360/18985670/089e904c-86c7-11e6-9256-2796aa1cbbd8.png">
